export const data = {
    products: [
    {
      id: '1',
      name: 'Valvoline Oil Stockists high quality',
      image: '/images/oil.jpg',
      price: 106.58,
      oldPrice: 202.87,
      countInStock: 10,
      rating: 5,
      numReviews: 70,
      percent: 20,
      description: 'high quality Valvoline Oil Stockists',
    },
    {
      id: '2',
      name: 'Racing Custom Wheels VF577',
      image: '/images/racing1.jpg',
      price: 179.49,
      oldPrice: 209.99,
      countInStock: 10,
      rating: 3,
      numReviews: 60,
      percent: 80,
      description: 'high quality Racing Custom Wheels VF577',
    },
    {
      id: '3',
      name: 'Racing Custom Wheels VF421',
      image: '/images/racing2.jpg',
      price: 38.24,
      oldPrice: 58.47,
      countInStock: 10,
      rating: 4.5,
      numReviews: 80,
      percent: 70,
      description: 'high quality Racing Custom Wheels VF421',
    },
    {
      id: '4',
      name: 'Kit Brembo DT BMW high quality',
      image: '/images/kit.jpg',
      price: 69.75,
      oldPrice: 98.65,
      countInStock: 10,
      rating: 3.5,
      numReviews: 99,
      percent: 65,
      description: 'high quality Kit Brembo DT BMW High',
    },
    {
      id: '5',
      name: 'Kit Brembo GT BMW',
      image: '/images/kit2.jpg',
      price: 69.75,
      oldPrice: 89.74,
      countInStock: 10,
      rating: 4.5,
      numReviews: 30,
      percent: 40,
      description: 'high quality Kit Brembo GT BMW',
    },
    {
      id: '6',
      name: 'Kit Brembo DT BMW',
      image: '/images/kit3.jpg',
      price: 26.45,
      oldPrice: 38.24,
      countInStock: 10,
      rating: 4.5,
      numReviews: 150,
      percent: 30,
      description: 'high quality Kit Brembo DT BMW',
    },
    {
      id: '7',
      name: 'Zipp Battery New 12V',
      image: '/images/battery.jpg',
      price: 26.45,
      oldPrice: 45.94,
      countInStock: 10,
      rating: 4.5,
      numReviews: 200,
      percent: 99,
      description: 'high quality Zipp Battery New 12V',
    },
    {
      id: '8',
      name: 'Racing Custom Wheels',
      image: '/images/racing3.jpg',
      price: 35.38,
      oldPrice: 39.24,
      countInStock: 10,
      rating: 4.5,
      numReviews: 65,
      percent: 45,
      description: 'high quality Racing Custom Wheels',
    },
    {
      id: '9',
      name: 'Dual Stack PowerTech',
      image: '/images/dual.jpg',
      price: 52.76,
      oldPrice: 89.74,
      countInStock: 7,
      rating: 4.5,
      numReviews: 18,
      percent: 80,
      description: 'high quality Dual Stack PowerTech',
    },
    {
      id: '10',
      name: 'Rubber Air Spring FD401',
      image: '/images/rubber.jpg',
      price: 49.99,
      oldPrice: 59.99,
      countInStock: 7,
      rating: 4.5,
      numReviews: 89,
      percent: 20,
      description: 'high quality Rubber Air Spring FD401',
    },
    {
      id: '11',
      name: 'Engine pistons',
      image: '/images/engine.jpg',
      price: 185.99,
      oldPrice: 230.99,
      countInStock: 7,
      rating: 4.5,
      numReviews: 46,
      percent: 30,
      description: 'high quality Engine pistons',
    },
    {
      id: '12',
      name: 'Hyst Brakes 1 Crop',
      image: '/images/hyst.jpg',
      price: 149.99,
      oldPrice: 200.99,
      countInStock: 7,
      rating: 4.5,
      numReviews: 18,
      percent: 10,
      description: 'high quality Hyst Brakes 1 Crop',
    },
    {
      id: '13',
      name: 'Road and Track Suspension',
      image: '/images/road.jpg',
      price: 49.99,
      oldPrice: 53.75,
      countInStock: 7,
      rating: 4.5,
      numReviews: 345,
      percent: 56,
      description: 'high quality Road and Track Suspension',
    },
    {
      id: '14',
      name: 'Altra Industrial Motion',
      image: '/images/Altra.jpg',
      price: 185.99,
      oldPrice: 199.99,
      countInStock: 7,
      rating: 4.5,
      numReviews: 78,
      percent: 75,
      description: 'high quality Altra Industrial Motion',
    },
    {
      id: '15',
      name: 'Racing Custom Wheels',
      image: '/images/Racing2S.jpg',
      price: 38.24,
      oldPrice: 59.99,
      countInStock: 7,
      rating: 4.5,
      numReviews: 456,
      percent: 100,
      description: 'high quality Racing Custom Wheels VF123',
    },
    {
      id: '16',
      name: 'Nuna car seats S134 High',
      image: '/images/Nuna.jpg',
      price: 38.24,
      oldPrice: 49.99,
      countInStock: 7,
      rating: 4.5,
      numReviews: 241,
      percent: 99,
      description: 'high quality Nuna car seats S134 High',
    },
    {
      id: '16',
      name: 'Dual Stack PowerTech',
      image: '/images/Dual2.jpg',
      price: 48.24,
      oldPrice: 58.24,
      countInStock: 7,
      rating: 4.5,
      numReviews: 134,
      percent: 70,
      description: 'high quality Dual Stack PowerTech',
    },
    {
      id: '17',
      name: 'Driver Side Headlight',
      image: '/images/Headlight.jpg',
      price: 53.75,
      oldPrice: 63.75,
      countInStock: 7,
      rating: 5,
      numReviews: 548,
      percent: 100,
      description: 'high quality Driver Side Headlight',
    },
  ],
}